/**
 * CuraParser
 * Parses G-code generated by Ultimaker Cura
 * Cura places metadata in header comments at the beginning of the file
 */

class CuraParser {
  /**
   * Parse Cura-style G-code
   * @param {string} content - G-code content
   * @returns {Object} Parsed data
   */
  parse(content) {
    const result = {
      // Time
      printTimeMinutes: null,
      printTimeSeconds: null,

      // Filament usage
      filamentUsedMm: null,
      filamentUsedMeters: null,
      filamentUsedGrams: null,
      filamentUsedCm3: null,

      // Filament properties (Cura doesn't always include these)
      filamentType: null,
      filamentDensity: null,
      filamentDiameter: null,

      // Print settings
      layerHeight: null,
      layerCount: null,
      nozzleDiameter: null,
      infillPercent: null,

      // Cura-specific
      flavor: null,
      generatedWith: null,
      printSpeed: null,
      bedTemperature: null,
      printTemperature: null,

      // Dimensions
      minX: null,
      minY: null,
      minZ: null,
      maxX: null,
      maxY: null,
      maxZ: null,
    };

    const lines = content.split('\n');

    // Cura puts info in header - scan first 200 lines
    const headerLines = lines.slice(0, 200);

    for (const line of headerLines) {
      // Skip non-comment lines
      if (!line.startsWith(';')) continue;

      // ============================================================
      // Time
      // ============================================================

      // ;TIME:7036 (in seconds)
      let match = line.match(/;TIME:(\d+)/);
      if (match) {
        result.printTimeSeconds = parseInt(match[1]);
        result.printTimeMinutes = result.printTimeSeconds / 60;
        continue;
      }

      // ;Print time: 1 hour 30 minutes
      match = line.match(/;Print time:\s*(?:(\d+)\s*hours?)?\s*(?:(\d+)\s*minutes?)?/i);
      if (match && !result.printTimeMinutes) {
        const hours = parseInt(match[1]) || 0;
        const minutes = parseInt(match[2]) || 0;
        result.printTimeMinutes = (hours * 60) + minutes;
        continue;
      }

      // ============================================================
      // Filament Usage
      // ============================================================

      // ;Filament used: 1.20047m
      match = line.match(/;Filament used:\s*([\d.]+)m/i);
      if (match) {
        result.filamentUsedMeters = parseFloat(match[1]);
        result.filamentUsedMm = result.filamentUsedMeters * 1000;
        continue;
      }

      // ;Filament used: 1200.47mm
      match = line.match(/;Filament used:\s*([\d.]+)mm/i);
      if (match && !result.filamentUsedMm) {
        result.filamentUsedMm = parseFloat(match[1]);
        continue;
      }

      // ;Filament weight = 15.2g (some Cura versions)
      match = line.match(/;Filament weight\s*[=:]\s*([\d.]+)\s*g/i);
      if (match) {
        result.filamentUsedGrams = parseFloat(match[1]);
        continue;
      }

      // ;Material volume: 3.83 (cm3)
      match = line.match(/;Material volume:\s*([\d.]+)/i);
      if (match) {
        result.filamentUsedCm3 = parseFloat(match[1]);
        continue;
      }

      // ============================================================
      // Print Settings
      // ============================================================

      // ;Layer height: 0.2
      match = line.match(/;Layer height:\s*([\d.]+)/i);
      if (match) {
        result.layerHeight = parseFloat(match[1]);
        continue;
      }

      // ;LAYER_COUNT:150
      match = line.match(/;LAYER_COUNT:(\d+)/);
      if (match) {
        result.layerCount = parseInt(match[1]);
        continue;
      }

      // ;Nozzle diameter: 0.4
      match = line.match(/;Nozzle diameter:\s*([\d.]+)/i);
      if (match) {
        result.nozzleDiameter = parseFloat(match[1]);
        continue;
      }

      // ;Infill: 20%
      match = line.match(/;Infill:\s*([\d.]+)%?/i);
      if (match) {
        result.infillPercent = parseFloat(match[1]);
        continue;
      }

      // ============================================================
      // Cura-Specific
      // ============================================================

      // ;FLAVOR:Marlin
      match = line.match(/;FLAVOR:(.+)/);
      if (match) {
        result.flavor = match[1].trim();
        continue;
      }

      // ;Generated with Cura_SteamEngine 5.4.0
      match = line.match(/;Generated with (.+)/i);
      if (match) {
        result.generatedWith = match[1].trim();
        continue;
      }

      // ;Print speed: 60
      match = line.match(/;Print speed:\s*([\d.]+)/i);
      if (match) {
        result.printSpeed = parseFloat(match[1]);
        continue;
      }

      // ;Build plate temperature: 60
      // ;Bed Temperature: 60
      match = line.match(/;(?:Build plate|Bed) [Tt]emperature:\s*([\d.]+)/i);
      if (match) {
        result.bedTemperature = parseFloat(match[1]);
        continue;
      }

      // ;Hotend temperature: 200
      // ;Print temperature: 200
      match = line.match(/;(?:Hotend|Print|Nozzle) [Tt]emperature:\s*([\d.]+)/i);
      if (match) {
        result.printTemperature = parseFloat(match[1]);
        continue;
      }

      // ============================================================
      // Dimensions
      // ============================================================

      // ;MINX:10.5
      match = line.match(/;MINX:([\d.-]+)/);
      if (match) {
        result.minX = parseFloat(match[1]);
        continue;
      }

      // ;MINY:10.5
      match = line.match(/;MINY:([\d.-]+)/);
      if (match) {
        result.minY = parseFloat(match[1]);
        continue;
      }

      // ;MINZ:0.2
      match = line.match(/;MINZ:([\d.-]+)/);
      if (match) {
        result.minZ = parseFloat(match[1]);
        continue;
      }

      // ;MAXX:100.5
      match = line.match(/;MAXX:([\d.-]+)/);
      if (match) {
        result.maxX = parseFloat(match[1]);
        continue;
      }

      // ;MAXY:100.5
      match = line.match(/;MAXY:([\d.-]+)/);
      if (match) {
        result.maxY = parseFloat(match[1]);
        continue;
      }

      // ;MAXZ:50.0
      match = line.match(/;MAXZ:([\d.-]+)/);
      if (match) {
        result.maxZ = parseFloat(match[1]);
        continue;
      }

      // ============================================================
      // Filament Properties
      // ============================================================

      // ;Filament type: PLA
      // ;Material type: PLA
      match = line.match(/;(?:Filament|Material) type:\s*(\w+)/i);
      if (match) {
        result.filamentType = match[1].toUpperCase();
        continue;
      }

      // ;Filament diameter: 1.75
      match = line.match(/;Filament diameter:\s*([\d.]+)/i);
      if (match) {
        result.filamentDiameter = parseFloat(match[1]);
        continue;
      }

      // ;Filament density: 1.24
      match = line.match(/;Filament density:\s*([\d.]+)/i);
      if (match) {
        result.filamentDensity = parseFloat(match[1]);
        continue;
      }
    }

    // Calculate grams from length (Cura often doesn't include weight)
    if (!result.filamentUsedGrams && result.filamentUsedMm) {
      const diameter = result.filamentDiameter || 1.75;
      const density = result.filamentDensity || 1.24; // PLA default
      const radiusCm = (diameter / 2) / 10;
      const lengthCm = result.filamentUsedMm / 10;
      const volumeCm3 = Math.PI * Math.pow(radiusCm, 2) * lengthCm;
      result.filamentUsedGrams = volumeCm3 * density;
    }

    // Calculate grams from volume
    if (!result.filamentUsedGrams && result.filamentUsedCm3) {
      const density = result.filamentDensity || 1.24;
      result.filamentUsedGrams = result.filamentUsedCm3 * density;
    }

    // Calculate meters from mm
    if (!result.filamentUsedMeters && result.filamentUsedMm) {
      result.filamentUsedMeters = result.filamentUsedMm / 1000;
    }

    // Round values
    if (result.filamentUsedGrams) {
      result.filamentUsedGrams = Math.round(result.filamentUsedGrams * 100) / 100;
    }
    if (result.printTimeMinutes) {
      result.printTimeMinutes = Math.round(result.printTimeMinutes * 10) / 10;
    }

    return result;
  }
}

// Register with main parser
if (typeof gcodeParser !== 'undefined') {
  gcodeParser.registerParser('cura', new CuraParser());
}
