/**
 * PrusaSlicerParser
 * Parses G-code generated by PrusaSlicer, SuperSlicer, OrcaSlicer, and Bambu Studio
 * These slicers use similar formats with metadata in comments at the end of the file
 */

class PrusaSlicerParser {
  /**
   * Parse PrusaSlicer-style G-code
   * @param {string} content - G-code content
   * @returns {Object} Parsed data
   */
  parse(content) {
    const result = {
      // Time
      printTimeMinutes: null,
      printTimeNormalMinutes: null,
      printTimeSilentMinutes: null,

      // Filament usage
      filamentUsedMm: null,
      filamentUsedCm3: null,
      filamentUsedGrams: null,
      filamentUsedMeters: null,

      // Filament properties
      filamentType: null,
      filamentDensity: null,
      filamentDiameter: null,
      filamentCost: null,

      // Print settings
      layerHeight: null,
      firstLayerHeight: null,
      nozzleDiameter: null,
      infillPercent: null,

      // Printer info
      printerModel: null,
      printerNotes: null,

      // Cost (if calculated by slicer)
      totalCost: null,
      filamentCostPerMm: null,
    };

    const lines = content.split('\n');

    // PrusaSlicer puts summary at the end - scan last 300 lines
    const tailLines = lines.slice(-300);

    for (const line of tailLines) {
      // Skip non-comment lines
      if (!line.startsWith(';')) continue;

      // ============================================================
      // Filament Usage
      // ============================================================

      // ; filament used [mm] = 1590.68
      let match = line.match(/;\s*filament used \[mm\]\s*=\s*([\d.]+)/i);
      if (match) {
        result.filamentUsedMm = parseFloat(match[1]);
        continue;
      }

      // ; filament used [cm3] = 3.83
      match = line.match(/;\s*filament used \[cm3\]\s*=\s*([\d.]+)/i);
      if (match) {
        result.filamentUsedCm3 = parseFloat(match[1]);
        continue;
      }

      // ; filament used [g] = 4.74
      match = line.match(/;\s*filament used \[g\]\s*=\s*([\d.]+)/i);
      if (match) {
        result.filamentUsedGrams = parseFloat(match[1]);
        continue;
      }

      // ; filament used [m] = 1.59
      match = line.match(/;\s*filament used \[m\]\s*=\s*([\d.]+)/i);
      if (match) {
        result.filamentUsedMeters = parseFloat(match[1]);
        continue;
      }

      // ============================================================
      // Print Time
      // ============================================================

      // ; estimated printing time (normal mode) = 25m 30s
      // ; estimated printing time (normal mode) = 1h 25m 30s
      // ; estimated printing time (normal mode) = 1d 2h 25m 30s
      match = line.match(/;\s*estimated printing time \(normal mode\)\s*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i);
      if (match) {
        const days = parseInt(match[1]) || 0;
        const hours = parseInt(match[2]) || 0;
        const minutes = parseInt(match[3]) || 0;
        const seconds = parseInt(match[4]) || 0;
        result.printTimeNormalMinutes = (days * 24 * 60) + (hours * 60) + minutes + (seconds / 60);
        result.printTimeMinutes = result.printTimeNormalMinutes;
        continue;
      }

      // ; estimated printing time (silent mode) = 1h 30m 45s
      match = line.match(/;\s*estimated printing time \(silent mode\)\s*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i);
      if (match) {
        const days = parseInt(match[1]) || 0;
        const hours = parseInt(match[2]) || 0;
        const minutes = parseInt(match[3]) || 0;
        const seconds = parseInt(match[4]) || 0;
        result.printTimeSilentMinutes = (days * 24 * 60) + (hours * 60) + minutes + (seconds / 60);
        continue;
      }

      // ; estimated printing time = 1h 25m 30s (OrcaSlicer format)
      match = line.match(/;\s*estimated printing time\s*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i);
      if (match && !result.printTimeMinutes) {
        const days = parseInt(match[1]) || 0;
        const hours = parseInt(match[2]) || 0;
        const minutes = parseInt(match[3]) || 0;
        const seconds = parseInt(match[4]) || 0;
        result.printTimeMinutes = (days * 24 * 60) + (hours * 60) + minutes + (seconds / 60);
        continue;
      }

      // ============================================================
      // Filament Properties
      // ============================================================

      // ; filament_type = PLA
      match = line.match(/;\s*filament_type\s*=\s*(.+)/i);
      if (match) {
        result.filamentType = match[1].trim().toUpperCase();
        continue;
      }

      // ; filament_density = 1.24
      match = line.match(/;\s*filament_density\s*=\s*([\d.]+)/i);
      if (match) {
        result.filamentDensity = parseFloat(match[1]);
        continue;
      }

      // ; filament_diameter = 1.75
      match = line.match(/;\s*filament_diameter\s*=\s*([\d.]+)/i);
      if (match) {
        result.filamentDiameter = parseFloat(match[1]);
        continue;
      }

      // ; filament_cost = 25.00
      match = line.match(/;\s*filament_cost\s*=\s*([\d.]+)/i);
      if (match) {
        result.filamentCost = parseFloat(match[1]);
        continue;
      }

      // ============================================================
      // Print Settings
      // ============================================================

      // ; layer_height = 0.2
      match = line.match(/;\s*layer_height\s*=\s*([\d.]+)/i);
      if (match) {
        result.layerHeight = parseFloat(match[1]);
        continue;
      }

      // ; first_layer_height = 0.25
      match = line.match(/;\s*first_layer_height\s*=\s*([\d.]+)/i);
      if (match) {
        result.firstLayerHeight = parseFloat(match[1]);
        continue;
      }

      // ; nozzle_diameter = 0.4
      match = line.match(/;\s*nozzle_diameter\s*=\s*([\d.]+)/i);
      if (match) {
        result.nozzleDiameter = parseFloat(match[1]);
        continue;
      }

      // ; fill_density = 15%
      match = line.match(/;\s*(?:fill_density|infill_density)\s*=\s*([\d.]+)%?/i);
      if (match) {
        result.infillPercent = parseFloat(match[1]);
        continue;
      }

      // ============================================================
      // Printer Info
      // ============================================================

      // ; printer_model = MK3S
      match = line.match(/;\s*printer_model\s*=\s*(.+)/i);
      if (match) {
        result.printerModel = match[1].trim();
        continue;
      }

      // ; printer_notes = My custom printer
      match = line.match(/;\s*printer_notes\s*=\s*(.+)/i);
      if (match) {
        result.printerNotes = match[1].trim();
        continue;
      }

      // ============================================================
      // Cost
      // ============================================================

      // ; total filament cost = 0.45
      match = line.match(/;\s*total (?:filament )?cost\s*=\s*([\d.]+)/i);
      if (match) {
        result.totalCost = parseFloat(match[1]);
        continue;
      }

      // ; filament_cost_per_mm = 0.000025
      match = line.match(/;\s*filament_cost_per_mm\s*=\s*([\d.]+)/i);
      if (match) {
        result.filamentCostPerMm = parseFloat(match[1]);
        continue;
      }
    }

    // Calculate grams from volume if not directly provided
    if (!result.filamentUsedGrams && result.filamentUsedCm3 && result.filamentDensity) {
      result.filamentUsedGrams = result.filamentUsedCm3 * result.filamentDensity;
    }

    // Calculate grams from length if still missing
    if (!result.filamentUsedGrams && result.filamentUsedMm) {
      const diameter = result.filamentDiameter || 1.75;
      const density = result.filamentDensity || 1.24; // PLA default
      const radiusCm = (diameter / 2) / 10;
      const lengthCm = result.filamentUsedMm / 10;
      const volumeCm3 = Math.PI * Math.pow(radiusCm, 2) * lengthCm;
      result.filamentUsedGrams = volumeCm3 * density;
    }

    // Calculate meters from mm
    if (!result.filamentUsedMeters && result.filamentUsedMm) {
      result.filamentUsedMeters = result.filamentUsedMm / 1000;
    }

    // Round values
    if (result.filamentUsedGrams) {
      result.filamentUsedGrams = Math.round(result.filamentUsedGrams * 100) / 100;
    }
    if (result.printTimeMinutes) {
      result.printTimeMinutes = Math.round(result.printTimeMinutes * 10) / 10;
    }

    return result;
  }
}

// Register with main parser
if (typeof gcodeParser !== 'undefined') {
  gcodeParser.registerParser('prusaslicer', new PrusaSlicerParser());
  gcodeParser.registerParser('superslicer', new PrusaSlicerParser());
  gcodeParser.registerParser('orcaslicer', new PrusaSlicerParser());
  gcodeParser.registerParser('bambustudio', new PrusaSlicerParser());
}
